# Use Intel Quantum SDK image
FROM intellabs/intel_quantum_sdk:latest

# Install Python tools and Jupyter Notebook
RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	ca-certificates \
	git \
	vim
